// <auto-generated />
using System;
using Assignment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment.Migrations
{
    [DbContext(typeof(C5_AssignmentContext))]
    partial class C5_AssignmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

                {
                    b.Property<int>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("BrandID");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("BrandId");

                    b.ToTable("Brand", (string)null);
                });

                {
                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("CartID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateConfirmed")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeliveryTypeId")
                        .HasColumnType("int")
                        .HasColumnName("DeliveryTypeID");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CartId");

                    b.HasIndex("DeliveryTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Cart", (string)null);
                });

                {
                    b.Property<int>("CartDetailId")
                        .HasColumnType("int")
                        .HasColumnName("CartDetailID");

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("CartID");

                    b.Property<int>("ColorID")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CartDetailId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartDetail", (string)null);
                });

                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);
                });

                {
                    b.Property<int>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("ColorID");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ColorId");

                    b.ToTable("Color", (string)null);
                });

                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("ColorID");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ProductId", "ColorId");

                    b.HasIndex("ColorId");

                    b.ToTable("ColorProduct", (string)null);
                });

                {
                    b.Property<int>("DeliveryTypeId")
                        .HasColumnType("int")
                        .HasColumnName("DeliveryTypeID");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DeliveryTypeId");

                    b.ToTable("DeliveryType", (string)null);
                });

                {
                    b.Property<int>("DiscountId")
                        .HasColumnType("int")
                        .HasColumnName("DiscountID");

                    b.Property<string>("DiscountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("DiscountId");

                    b.ToTable("Discount", (string)null);
                });

                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int")
                        .HasColumnName("DiscountID");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ProductId", "DiscountId");

                    b.HasIndex("DiscountId");

                    b.ToTable("DiscountProduct", (string)null);
                });

                {
                    b.Property<int>("ImageId")
                        .HasColumnType("int")
                        .HasColumnName("ImageID");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("Image", (string)null);
                });

                {
                    b.Property<int>("NationalId")
                        .HasColumnType("int")
                        .HasColumnName("NationalID");

                    b.Property<string>("NatinalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("NationalId");

                    b.ToTable("National", (string)null);
                });

                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

                {
                    b.Property<int>("ProductDetailId")
                        .HasColumnType("int")
                        .HasColumnName("ProductDetailID");

                    b.Property<int>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("BrandID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageId")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ImageID");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("date");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NationalId")
                        .HasColumnType("int")
                        .HasColumnName("NationalID");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("StyleId")
                        .HasColumnType("int")
                        .HasColumnName("StyleID");

                    b.HasKey("ProductDetailId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NationalId");

                    b.HasIndex("StyleId");

                    b.ToTable("ProductDetail", (string)null);
                });

                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("RoleId");

                    b.ToTable("Role", (string)null);
                });

                {
                    b.Property<int>("StyleId")
                        .HasColumnType("int")
                        .HasColumnName("StyleID");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("StyleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StyleId");

                    b.ToTable("Style", (string)null);
                });

                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

                {
                        .WithMany("Carts")
                        .HasForeignKey("DeliveryTypeId")
                        .HasConstraintName("FK_Cart_DeliveryType");


                    b.Navigation("DeliveryType");

                    b.Navigation("User");
                });

                {
                        .WithMany("CartDetails")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("FK_CartDetail_CartDetail");

                        .WithMany("CartDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_CartDetail_Product");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

                {
                        .WithMany("ColorProducts")
                        .HasForeignKey("ColorId")
                        .IsRequired()
                        .HasConstraintName("FK_ColorProduct_Color");

                        .WithMany("ColorProducts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ColorProduct_ProductDetail");

                    b.Navigation("Color");

                    b.Navigation("Product");
                });

                {
                        .WithMany("DiscountProducts")
                        .HasForeignKey("DiscountId")
                        .IsRequired()
                        .HasConstraintName("FK_DiscountProduct_Discount");

                        .WithMany("DiscountProducts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_DiscountProduct_ProductDetail");

                    b.Navigation("Discount");

                    b.Navigation("Product");
                });

                {
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Image_ProductDetail");

                    b.Navigation("Product");
                });

                {
                        .WithOne("Product")
                        .IsRequired()
                        .HasConstraintName("FK_Products_ProductDetail");

                    b.Navigation("ProductNavigation");
                });

                {
                        .WithMany("ProductDetails")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductDetail_Brand");

                        .WithMany("ProductDetails")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductDetail_Category");

                        .WithMany("ProductDetails")
                        .HasForeignKey("NationalId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductDetail_National");

                        .WithMany("ProductDetails")
                        .HasForeignKey("StyleId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductDetail_Style");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("National");

                    b.Navigation("Style");
                });

                {
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Role");
                });

                {
                    b.Navigation("ProductDetails");
                });

                {
                    b.Navigation("CartDetails");
                });

                {
                    b.Navigation("ProductDetails");
                });

                {
                    b.Navigation("ColorProducts");
                });

                {
                    b.Navigation("Carts");
                });

                {
                    b.Navigation("DiscountProducts");
                });

                {
                    b.Navigation("ProductDetails");
                });

                {
                    b.Navigation("CartDetails");

                    b.Navigation("ColorProducts");

                    b.Navigation("DiscountProducts");

                    b.Navigation("Images");

                    b.Navigation("Product")
                        .IsRequired();
                });

                {
                    b.Navigation("Users");
                });

                {
                    b.Navigation("ProductDetails");
                });

                {
                });
#pragma warning restore 612, 618
        }
    }
}
